- name: Deploy EC2 instances in AWS
  hosts: localhost
  gather_facts: false
  environment:
    AWS_REGION: us-east-2
  vars_prompt:
    - name: num_instances
      prompt: How many instances to create?
      private: false
    - name: base_name
      prompt: What to use as the base name for resources?
      private: false
    - name: http_port
      prompt: What port to use for HTTP requests?
      private: false
  tasks:
    - name: Ensure local SSH directory exists
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.ssh"
        state: directory
        mode: "0700"

    - name: Create security group
      amazon.aws.ec2_security_group:
        name: "{{ base_name }}"
        description: "{{ base_name }}"
        rules:
          - proto: tcp
            ports: ["{{ http_port }}"]
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0
      register: aws_security_group

    - name: Create a new EC2 key pair
      amazon.aws.ec2_key:
        name: ansible-ch3
        file_name: "{{ lookup('env', 'HOME') }}/.ssh/ansible-ch3.key"
        state: present
      no_log: true
      register: aws_ec2_key_pair

    - name: Ensure private key permissions
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.ssh/ansible-ch3.key"
        mode: "0600"

    - name: Create EC2 instances with Amazon Linux 2023 AMI
      loop: "{{ range(num_instances | int) | list }}"
      amazon.aws.ec2_instance:
        name: "{{ '%s-%d' | format(base_name, item) }}"
        key_name: "{{ aws_ec2_key_pair.key.name }}"
        instance_type: t3.micro
        security_group: "{{ aws_security_group.group_id }}"
        image_id: ami-0900fe555666598a2
        wait: true
        wait_timeout: 300
        tags:
          Ansible: "{{ base_name }}"
